
CREATE TABLE users (
user_id SERIAL PRIMARY KEY,
username VARCHAR(20) UNIQUE NOT NULL,
password VARCHAR(20) NOT NULL,
email VARCHAR(40) UNIQUE NOT NULL
);

DROP TABLE users
DROP TABLE leaderboard

INSERT INTO users (username, password, email)
VALUES 
('mikecordero42', 'bossman24', 'mikec42@gmail.com'),
('joeybones5', 'greenobot', 'joeyb5@gmail.com'),
('samanthafitz33', 'sunshine22', 'samfitz92@gmail.com');

CREATE TABLE leaderboard (
leaderboard_id SERIAL PRIMARY KEY,
score INT NULL,
user_id_fk INt REFERENCES users (user_id) NOT NULL
);

CREATE TABLE mixed_letters (
mixed_letters_id SERIAL PRIMARY KEY,
jumbled_letters VARCHAR(6) NOT NULL
);

INSERT INTO mixed_letters (jumbled_letters)
VALUES
('PMAELM'),
('SECDAD'),
('RBINDY'),
('XMIBRL'),
('XBOMLA'),
('UBKCIN'),
('DYRHAM'),
('TERCSL'),
('OTBAOD'),
('CTUOHX'),
('KEAWAL'),
('VYGARC'),
('HTHCAF'),
('RTLOLA'),
('GSUTNL');

CREATE TABLE words (
words_id SERIAL PRIMARY KEY,
word VARCHAR(6) NOT NULL,
mixed_letters_fk int REFERENCES mixed_letters (mixed_letters_id) NOT NULL
);

DROP TABLE mixed_letters
DROP TABLE words
DROP TABLE users
DROP table leaderboard

INSERT INTO words (word, mixed_letters_fk)
VALUES
('AMPLE', 1),
('LEMMA', 1),
('MAPLE', 1),
('LAMP', 1),
('MALM', 1),
('PALM', 1)
('ALME', 1),
('LAME', 1),
('LEAP', 1),
('MALE', 1),
('MEAL', 1), 
('PALE', 1),
('PEAL', 1),
('PLEA', 1),
('AMP', 1),
('MAM', 1),
('MAP', 1),
('ALP', 1),
('APE', 1),
('ELM', 1),
('LAM', 1), 
('LAP', 1),
('PAL', 1),
('PEA', 1),
('ALE', 1),
('MM', 1),
('AM', 1),
('EM', 1),
('MA', 1),
('ME', 1),
('PA', 1), 
('PE', 1),
('AE', 1),
('AL', 1),
('EL', 1),
('LA', 1),
('A', 1)
('CASED', 2),
('ACED', 2),
('CADS', 2),
('DACE', 2),
('SCAD', 2),
('ACES', 2),
('ADDS', 2),
('CASE', 2),
('DADS', 2),
('DEAD', 2),
('CAD', 2),
('ACE', 2),
('ADD', 2),
('DAD', 2),
('SAC', 2),
('SEC', 2),
('ADS', 2),
('DAS', 2),
('SAD', 2),
('SEA', 2),
('AD', 2),
('DA', 2),
('DE', 2),
('ED', 2),
('AE', 2),
('AS', 2),
('ES', 2),
('A', 2),
('BRINY', 3),
('BIND', 3),
('BIRD', 3),
('RIND', 3),
('DRY', 3),
('BID', 3),
('DIB', 3),
('YIN', 3),
('BIN', 3),
('NIB', 3),
('RIB', 3),
('DIN', 3),
('RID', 3),
('BY', 3),
('BI', 3),
('ID', 3),
('IN', 3),
('I', 3),
('BRIM', 4),
('LIMB', 4),
('BIRL', 4),
('MIX', 4),
('LIB', 4),
('MIL', 4),
('RIB', 4),
('RIM', 4),
('XI', 4),
('BIRL', 4),
('MI', 4),
('LI', 4),
('I', 4), 
('MOXA', 5), 
('AMBO', 5), 
('BALM', 5), 
('BLAM', 5), 
('LAMB', 5), 
('BOLA', 5), 
('LOAM', 5), 
('MOLA', 5), 
('BOX', 5), 
('MAX', 5), 
('LAX', 5), 
('LOX', 5), 
('BAM', 5), 
('MOB', 5), 
('ALB', 5), 
('BOA', 5), 
('LAB', 5), 
('LAM', 5), 
('LOB', 5), 
('MOA', 5), 
('MOL', 5), 
('OBA', 5), 
('OMA', 5), 
('AX', 5), 
('OX', 5), 
('AB', 5), 
('AM', 5), 
('BA', 5), 
('BO', 5), 
('MA', 5), 
('MO', 5), 
('OM', 5), 
('AL', 5), 
('LA', 5), 
('LO', 5), 
('A', 5),
('BUCK', 6),
('BUNK', 6),
('NICK', 6),
('ICK', 6),
('CUB', 6),
('INK', 6),
('KIN', 6),
('BUN', 6),
('BIN', 6),
('NIB', 6),
('UNI', 6),
('BIN', 6),
('UN', 6),
('IN', 6),
('BI', 6),
('NU', 6),
('I', 6),
('HARDY', 7),
('HYDRA', 7),
('ARMY', 7),
('HARM', 7),
('DRAY', 7),
('HARD', 7),
('YARD', 7),
('DRAM', 7),
('HAY', 7),
('YAH', 7),
('HAM', 7),
('MAY', 7),
('YAM', 7),
('DAH', 7),
('DAY', 7),
('DRY', 7),
('HAD', 7),
('DAM', 7),
('MAD', 7),
('RAH', 7),
('RAY', 7),
('ARM', 7),
('MAR', 7),
('RAM', 7),
('RAD', 7),
('HM', 7),
('MY', 7),
('AH', 7),
('AY', 7),
('HA', 7),
('YA', 7),
('AM', 7),
('MA', 7),
('AD', 7),
('DA', 7),
('AR', 7),
('A', 7),
('CELTS', 8),
('CERTS', 8),
('CREST', 8),
('CELS', 8),
('CELT', 8),
('CERT', 8),
('RECS', 8),
('SECT', 8),
('ERST', 8),
('LEST', 8),
('LETS', 8),
('REST', 8),
('RETS', 8),
('CEL', 8),
('REC', 8),
('SEC', 8),
('ELS', 8),
('ERS', 8),
('EST', 8),
('LET', 8),
('RES', 8),
('RET', 8),
('SET', 8),
('TEL', 8),
('EL', 8),
('ER', 8),
('ES', 8),
('ET', 8),
('RE', 8),
('TE', 8),
('ADOBO', 9),
('TABOO', 9),
('BOAT', 9),
('BOOT', 9),
('TOAD', 9),
('BAD', 9),
('BOD', 9),
('DAB', 9),
('BAT', 9),
('BOA', 9),
('BOO', 9),
('BOT', 9),
('OBA', 9),
('TAB', 9),
('ADO', 9),
('DOT', 9),
('TAB', 9),
('TOD', 9),
('OAT', 9),
('TAO', 9),
('TOO', 9),
('AB', 9),
('BO', 9),
('BA', 9),
('AD', 9),
('DA', 9),
('DO', 9),
('OD', 9),
('AT', 9),
('TO', 9),
('A', 9),
('COUTH', 10),
('TOUCH', 10),
('OUCH', 10),
('THOU', 10),
('COX', 10),
('TUX', 10),
('OCH', 10),
('HOT', 10),
('HUT', 10),
('THO', 10),
('COT', 10),
('CUT', 10),
('OUT', 10),
('OX', 10),
('XU', 10),
('HO', 10),
('OH', 10),
('UH', 10),
('TO', 10),
('UT', 10),
('AWAKE', 11),
('AKELA', 11),
('WAKE', 11),
('WALK', 11),
('WEAK', 11),
('WEKA', 11),
('KALE', 11),
('LAKE', 11),
('LEAK', 11),
('WHALE', 11),
('WEAL', 11),
('ELK', 11),
('KEA', 11),
('LEK', 11),
('AWE', 11),
('AWl', 11),
('LAW', 11),
('ALA', 11),
('LEA', 11),
('KA', 11),
('AW', 11),
('EW', 11),
('WE', 11),
('AA', 11),
('AL', 11),
('EL', 11),
('LA', 11),
('A', 11),
('GRAVY', 12),
('CAVY', 12),
('CAGY', 12),
('VARY', 12),
('RACY', 12),
('GRAY', 12),
('CRAG', 12),
('CAY', 12),
('CRY', 12),
('VAC', 12),
('GAY', 12),
('RAY', 12),
('VAR', 12),
('YAR', 12),
('ARC', 12),
('CAR', 12),
('GAR', 12),
('RAG', 12),
('AY', 12),
('YA', 12),
('AG', 12),
('AR', 12),
('A', 12),
('HATCH', 13),
('HAFT', 13),
('HATH', 13),
('CHAT', 13),
('FACT', 13),
('TACH', 13),
('FAH', 13),
('HAH', 13),
('CAF', 13),
('AFT', 13),
('FAT', 13),
('HAT', 13),
('ACT', 13),
('CAT', 13),
('AH', 13),
('FA', 13),
('HA', 13),
('AT', 13),
('TA', 13),
('A', 13),
('ALLOT', 14),
('ATOLL', 14),
('LORAL', 14),
('TOLAR', 14),
('TROLL', 14),
('ALTO', 14),
('LOTA', 14),
('ORAL', 14),
('ROLL', 14),
('ROTA', 14),
('TALL', 14),
('TARO', 14),
('TOLL', 14),
('ALL', 14),
('ALT', 14),
('ART', 14),
('LAR', 14),
('LAT', 14),
('LOT', 14),
('OAR', 14),
('OAT', 14),
('ORA', 14),
('ORT', 14),
('RAT', 14),
('ROT', 14),
('TAO', 14),
('TAR', 14),
('TOR', 14),
('AL', 14),
('AR', 14),
('AT', 14),
('LA', 14),
('LO'', 14),
('OR', 14),
('TA', 14),
('TO', 14),
('A', 14),
('GLUTS', 15),
('LUNGS', 15),
('SLUNG', 15),
('STUNG', 15),
('TUNGS', 15),
('GLUT', 15),
('GNUS', 15),
('GUNS', 15),
('GUST', 15),
('LUGS', 15),
('LUNG', 15),
('SLUG', 15),
('SNUG', 15),
('SUNG', 15),
('TUGS', 15),
('LUST', 15),
('NUTS', 15),
('STUN', 15),
('TUNS', 15),
('GNU', 15),
('GUN', 15),
('GUT', 15),
('LUG', 15),
('TUG', 15),
('NUT', 15),
('SUN', 15),
('TUN', 15),
('NU', 15),
('UN', 15),
('US', 15),
('UT', 15);



SELECT * FROM words WHERE mixed_letters_fk = 2;
--IF '' IS equal TO words WHERE mixed_letters_fk = 2 THEN ADD 1 TO score WHERE user_id = ?